# Generated by Django 5.2 on 2025-04-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('rivaanah-admin3304$', 'Rivaanah Admin')], default='customer', max_length=20),
        ),
    ]
