# Generated by Django 5.2 on 2025-07-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
