# Generated by Django 5.2 on 2025-04-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_stock_product_available_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
