# Generated by Django 5.2 on 2025-06-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_cartitem_id_alter_order_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.JSONField(default=dict),
        ),
    ]
