# Generated by Django 5.2 on 2025-06-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_product_type_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('saree', 'Saree'), ('lehenga', 'Lehenga'), ('kurta', 'Kurta'), ('Shirts', 'shirts')], max_length=50),
        ),
    ]
