# Generated by Django 5.2 on 2025-06-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('saree', 'Saree'), ('lehenga', 'Lehenga'), ('kurta', 'Kurta'), ('Shirts', 'shirts'), ('tshirts', 'Tshirts')], max_length=50),
        ),
    ]
